apiVersion: v1
kind: Service
metadata:
  name: capstone
spec:
  type: LoadBalancer
  selector:
    app: capstone
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deploy
spec:
  selector:
    matchLabels:
      app: capstone
  replicas: 3
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - name: capstone-pod
          image: welith95/capstone
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 10